# This file was generated by GoReleaser. DO NOT EDIT.
cask "openai" do
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/openai/openai-cli/releases/download/v#{version}/openai_#{version}_macos_amd64.zip"
      sha256 "9081d8710d7df91e26e7d7b2b80cb46eb0202296bb091ceac6233f69a8fa5ba1"
    end
    on_arm do
      url "https://github.com/openai/openai-cli/releases/download/v#{version}/openai_#{version}_macos_arm64.zip"
      sha256 "e1994fd07e34300f57778a0e983f2f21012f1cad1732f8c82547b9025d18fd7a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/openai/openai-cli/releases/download/v#{version}/openai_#{version}_linux_amd64.tar.gz"
      sha256 "d5db7152108c69b21d1e8f29a9f31570f5f8bee1fbc036a3b2e502e5465f35ed"
    end
    on_arm do
      url "https://github.com/openai/openai-cli/releases/download/v#{version}/openai_#{version}_linux_arm64.tar.gz"
      sha256 "e238f5b0c52dc7bd4438c1d03708f6c3c5f6c6e8f996ed24492465a9b1db4475"
    end
  end

  name "openai"
  desc "The official CLI for the OpenAI API."
  homepage "https://developers.openai.com/api/docs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openai"
  manpage "man/man1/openai.1.gz"
  bash_completion "completions/openai.bash"
  fish_completion "completions/openai.fish"
  zsh_completion "completions/openai.zsh"

  # No zap stanza required

end
